config/routes.rb
Rails.application.routes.draw do

  namespace :admin, path: '/admin' do
    get 'dashboard/index'
    root to: redirect('admin/dashboard/index')
    resources :images
    resources :columns do
      resources :posts
    end
    resources :posts, except: [:show] do
      post :convert, on: :collection
    end
    resources :users
  end

  devise_for :users, controllers: { sessions: "users/sessions" }, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  root 'posts#index'
  resources :posts, only: [:index, :show], param: :slug
  resources :users, only:[:show], param: :name
  resources :columns, only:[:show], param: :slug

  get '/wechat' => 'wechat#index'
  post '/wechat' => 'wechat#message'

  match '/tag/:tag' => 'tags#show', via: :get, as: :tag
  match '/site_map.:format' => 'posts#site_map', via: :get, constraints: { format: 'xml' }, as: :site_map

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id           :integer          not null, primary key
#  title        :string(255)
#  raw_content  :text
#  html_content :text
#  created_at   :datetime
#  updated_at   :datetime
#  user_id      :integer
#  column_id    :integer
#  slug         :string(255)
#  cover        :string(255)
#  summary      :text
#  views_count  :integer          default(0)
#

class Post < ActiveRecord::Base
  validates_presence_of :title, :raw_content, :html_content, :slug
  validates_uniqueness_of :title, :slug

  belongs_to :column, counter_cache: true
  belongs_to :author, class_name: User.to_s, foreign_key: 'user_id'

  acts_as_taggable
  mount_uploader :cover, ImageUploader

  scope :related,    -> { includes(:author, :column) }
  scope :recent,    -> { order('created_at desc') }

  def increase_views_count
  	self.update_column(:views_count, self.views_count.next)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  load_and_authorize_resource

  def index
    @posts = Column.find(params[:column_id]).posts rescue Post
    @posts = @posts.includes(:column, :author).order("created_at desc")
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to  admin_posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_path(slug: @post.slug), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def convert
    render :text => GitHub::Markdown.render_gfm(params[:content]).html_safe
  end

  private
    def post_params
      result = params.require(:post).permit(:title, :raw_content, :slug, :tag_list, :cover, :column_id, :summary)
      result[:html_content] = GitHub::Markdown.render_gfm(result[:raw_content]).html_safe
      result
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.related.recent
  end

  def show
  	#error when not found
  	@post = Post.find_by_slug!(params[:slug])
  	@post.increase_views_count
  end

  def site_map
  	@posts = Post.related.recent
  	response.headers['content-type'] = 'application/xml'
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
	def convert_raw_content(raw_content)
		return raw_content if raw_content.blank?
		raw_content.gsub("\r\n", "\r")
	end
end

app/helpers/posts_helper.rb
module PostsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/views/posts/_comments.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = '<%= Settings.disqus.shortname %>';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_footer.html.slim
footer.post-footer
  figure.author-image
    a.img href="#{user_path(name: @post.author.name)}" style="background-image: url(#{@post.author.avatar.url})"
  .author-info
    h3
      = link_to @post.author.display_name, user_path(name: @post.author.name)
    p.autho-bio  = @post.author.introduce

app/views/posts/_post.html.slim
article.post.column-info
  div.top-info
    div.top.left
      span
        = link_to "/columns/#{post.column.try(:slug)}", class: "#{post.column.try(:slug)}" do
          = "#{post.column.try(:name)}"
        = " / #{post.column.try(:slug)}"
    div.top.right
      = link_to post.author.try(:display_name) || '佚名', user_path(name: post.author.try(:name))
      |&nbsp;•&nbsp;
      = smart_time_ago post.created_at
  div.left-col
    div.left.left-col
      div.thumb-180
        = link_to post_path(slug: post.slug), class: "info_flow_news_image" do
          = image_tag post.cover.thumb.url if post.cover.thumb.url.present?
  div.right-col
    h1
      = link_to raw(post.title), post_path(slug: post.slug), target: "_blank", class: "info_flow_news_title"
    p.summary = post.summary

app/views/posts/_table_content.html.slim
div.sidebar-nav style="margin-bottom: 20px;"
  h3 Page Nav
  div.sidebar-list#table-content

javascript:
  $('#table-content').toc({
    'selectors': 'h1,h2,h3',
    'container': '.post-content',
    'smoothScrolling': true,
    'prefix': 'toc',
    'onHighlight': function(el) {},
    'highlightOnScroll': true,
    'highlightOffset': 100,
    'anchorName': function(i, heading, prefix) {
        return prefix+i;
    },
    'headerText': function(i, heading, $heading) {
        return $heading.text();
    },
		'itemClass': function(i, heading, $heading, prefix) {
		  return 'toc-'+$heading[0].tagName.toLowerCase();
		}
  });

app/views/posts/_tags.html.slim
div.sidebar-nav#tag-list
  h3 Tags
  div.sidebar-list
    - tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class|
      = link_to tag.name, tag_path(tag: tag.name), :class => css_class

app/views/posts/index.html.slim
= render_metas

div.bs-docs-header#content
  div.container
    h1 Techer Man Blog
    p Techer Man 是一个的技术博客， Enjoy Your Time!

div.container
  div.rows style="margin-top:10px;"
    div.col-lg-12
    
      div.col-lg-9
        div.articles
          = render @posts

      div.col-lg-3
        .search-placeholder
        = render_cell :side, :tags_cloud
        = render_cell :side, :hot_posts

app/views/posts/show.html.slim
= content_for :title, @post.title

= render_metas title: @post.title, description: @post.summary, url: post_url(slug: @post.slug), avatar: @post.cover.big_thumb.url || @post.author.avatar.small_thumb.url

div.container
  div.rows style="margin-top:10px;"
    div.col-lg-12

      div.col-lg-9.post-show
        = image_tag @post.cover.url if @post.cover.to_s.present?

        header.single-post-header__meta
          .single-post__postmeta
            a href="#{user_path(name: @post.author.name)}" #{ @post.author.display_name }
            |&nbsp;•&nbsp;
            = smart_time_ago(@post.created_at)
          h1.single-post__title = raw(@post.title)

        div.post-content
          = raw @post.html_content

        div
          - @post.tag_list.each do |tag|
            span style="margin: 0 5px;"
              i.glyphicon.glyphicon-tag
              |&nbsp;
              = link_to tag, tag_path(tag)
        div style="margin-top:20px;"
          - if can? :edit, @post
            = link_to 'Edit', edit_admin_post_path(@post), target: 'new'

        = render 'footer'

        = render 'comments'
        
      div.col-lg-3
        = render 'table_content'
        .search-placeholder
        = render_cell :side, :tags_cloud
        = render_cell :side, :hot_posts

javascript:
  $(document).ready(function(){
    $(".post-content a").attr("target", '_blank');
  });

app/views/posts/site_map.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <% @posts.each do |post| %>
    <url>
      <loc><%= post_url slug: post.slug %></loc>
      <lastmod><%= post.created_at.strftime("%F") %></lastmod>
      <changefreq>always</changefreq>
      <priority>1.0</priority>
    </url>
  <% end %>
</urlset>