config/routes.rb
Rails.application.routes.draw do

  namespace :admin, path: '/admin' do
    get 'dashboard/index'
    root to: redirect('admin/dashboard/index')
    resources :images
    resources :columns do
      resources :posts
    end
    resources :posts, except: [:show] do
      post :convert, on: :collection
    end
    resources :users
  end

  devise_for :users, controllers: { sessions: "users/sessions" }, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  root 'posts#index'
  resources :posts, only: [:index, :show], param: :slug
  resources :users, only:[:show], param: :name
  resources :columns, only:[:show], param: :slug

  get '/wechat' => 'wechat#index'
  post '/wechat' => 'wechat#message'

  match '/tag/:tag' => 'tags#show', via: :get, as: :tag
  match '/site_map.:format' => 'posts#site_map', via: :get, constraints: { format: 'xml' }, as: :site_map

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/column.rb
# == Schema Information
#
# Table name: columns
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  slug        :string(255)
#  introduce   :text
#  created_at  :datetime
#  updated_at  :datetime
#  posts_count :integer
#

class Column < ActiveRecord::Base
  validates :name, :introduce, :slug, presence: true
  validates_uniqueness_of :name, :slug

  has_many :posts, dependent: :destroy
end

app/controllers/admin/columns_controller.rb
class Admin::ColumnsController < Admin::BaseController
  load_and_authorize_resource
  before_action :set_column, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @columns = Column.order("created_at desc")
    respond_with([:admin, @columns])
  end

  def show
    respond_with([:admin, @column])
  end

  def new
    @column = Column.new
    respond_with([:admin, @column])
  end

  def edit
  end

  def create
    @column = Column.new(column_params)
    @column.save
    respond_with([:admin, @column])
  end

  def update
    @column.update(column_params)
    respond_with([:admin, @column])
  end

  def destroy
    @column.destroy
    respond_with([:admin, @column])
  end

  private
    def set_column
      @column = Column.find(params[:id])
    end

    def column_params
      params.require(:column).permit(:name, :slug, :introduce)
    end
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  def show
    @column = Column.find_by_slug!(params[:slug])
    @posts = @column.posts.includes(:author).order("created_at desc")
  end
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/views/admin/columns/_form.html.slim
= simple_form_for [:admin, @column], class: 'form-horizontal' do |f|
  - if @column.errors.any?
    #error_explanation
      h2 = "#{pluralize(@column.errors.count, "error")} prohibited this column from being saved:"
      ul
        - @column.errors.full_messages.each do |message|
          li = message

  = f.input :name, input_html:{ class: 'form-control' }
  = f.input :slug, input_html:{ class: 'form-control' }
  = f.input :introduce, :input_html => { 'rows' => 3, class: 'form-control'}
  = f.button :submit, data: { disable_with: "submitting..." }, class:"btn btn-primary", style: 'margin-top: 10px;'

app/views/admin/columns/edit.html.slim
h1 Editing column

== render 'form'

= link_to 'Show', [:admin, @column]
'|
= link_to 'Back', admin_columns_path

app/views/admin/columns/index.html.slim
= link_to 'New Column', new_admin_column_path, class: 'btn btn-primary'

table.table.table-hover
  thead
    tr
      th Name
      th Slug
      th Introduce
      th PostsCount
      th CreatedAt
      th Operations

  tbody
    - @columns.each do |column|
      tr
        td = link_to column.name, [:admin, column]
        td = link_to column.slug, [:admin, column]
        td = column.introduce
        td = link_to column.posts_count.to_i, admin_column_posts_path(column)
        td = smart_time_ago column.created_at
        td
          = link_to edit_admin_column_path(column) do
            i.glyphicon.glyphicon-pencil
          |&nbsp;&nbsp;
          = link_to [:admin, column], data: {:confirm => 'Are you sure?'}, :method => :delete do
            i.glyphicon.glyphicon-remove

app/views/admin/columns/new.html.slim
h1 New column

= render 'form'
= link_to 'Back', admin_columns_path

app/views/admin/columns/show.html.slim
p#notice = notice

p
  strong Name:
  = @column.name
p
  strong Slug:
  = @column.slug
p
  strong Introduce:
  = @column.introduce

= link_to 'Edit', edit_admin_column_path(@column)
'|
= link_to 'Back', admin_columns_path