config/routes.rb
Rails.application.routes.draw do

  namespace :admin, path: '/admin' do
    get 'dashboard/index'
    root to: redirect('admin/dashboard/index')
    resources :images
    resources :columns do
      resources :posts
    end
    resources :posts, except: [:show] do
      post :convert, on: :collection
    end
    resources :users
  end

  devise_for :users, controllers: { sessions: "users/sessions" }, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  root 'posts#index'
  resources :posts, only: [:index, :show], param: :slug
  resources :users, only:[:show], param: :name
  resources :columns, only:[:show], param: :slug

  get '/wechat' => 'wechat#index'
  post '/wechat' => 'wechat#message'

  match '/tag/:tag' => 'tags#show', via: :get, as: :tag
  match '/site_map.:format' => 'posts#site_map', via: :get, constraints: { format: 'xml' }, as: :site_map

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_google_tracker.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  <% ga_user_id = if @current_user then [@current_user.id, @current_user.display_name].join('-') else 0 end %>
  window.ga_user_id = '<%= ga_user_id %>'
  ga('create', 'UA-43685115-3', { 'userId': '<%= ga_user_id %>' });
  ga('send', 'pageview');
</script>

app/views/layouts/_metas.html.slim
- content_for :metas do
  
  /!twitter meta
  meta content="@#{@site_name}" name="twitter:site"
  meta content="summary" name="twitter:card"
  meta content="#{@title}" name="twitter:title"
  meta content="#{@description}" name="twitter:description"
  meta content="#{@avatar}" name="twitter:image:src"

  /!og meta
  meta content="#{@site_name}" property="og:site_name"
  meta content="post" property="og:type"
  meta content="#{@avatar}" property="og:image"
  meta content="#{@title}" property="og:title"
  meta content="#{@url}" property="og:url"
  meta content="#{@description}" property="og:description"

app/views/layouts/_script.html.slim
javascript:
  $(document).ready(function(ret, status){
      $(".timeago").timeago();
  });

app/views/layouts/admin.html.slim
/!DOCTYPE html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title = content_for?(:title) ? yield(:title) : Settings.site.ttile
    = csrf_meta_tags

    /!-- Le HTML5 shim, for IE6-8 support of HTML elements
    |<!--[if lt IE 9]>
    | <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    |<![endif]-->


    /!-- For third-generation iPad with high-resolution Retina display:
    /!-- Size should be 144 x 144 pixels
    /!= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'

    /!-- For iPhone with high-resolution Retina display:
    /!-- Size should be 114 x 114 pixels
    /!= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'

    /!-- For first- and second-generation iPad:
    /!-- Size should be 72 x 72 pixels
    /!= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'

    /!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    /!-- Size should be 57 x 57 pixels
    /!= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'

    /!-- For all other devices
    /!-- Size should be 32 x 32 pixels
    = favicon_link_tag '/favicon.ico', :rel => 'shortcut icon'

    = stylesheet_link_tag "application", :media => "all"
    script src="/ace/ace.js"
    = javascript_include_tag "admin"

  body
    header.nnavbar.navbar-static-top.navbar-inverse
      div.container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to Settings.site.title, admin_root_path, class: 'navbar-brand'
        div.navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            - if can? :read, Column
              li class="#{ nav_active :columns, controller_name }"
                = link_to "Columns", admin_columns_path
            - if can? :read, Post
              li class="#{ nav_active :posts, controller_name }"
                = link_to "Posts", admin_posts_path
            - if can? :read, User
              li class="#{ nav_active :users, controller_name }"
                = link_to "Users", admin_users_path
            li
              = link_to "主页", root_path, target: '_blank'

          ul.nav.nav-list style="float:right;"
            - if current_user
              li
                = link_to current_user.display_name, "/#", class: 'inline-block'
                ||
                = link_to "退出", destroy_user_session_path, method: :delete, class: 'inline-block'

    div.container
      div.rows style="margin-top:10px;"
        div.col-lg-12
          = show_flashes
          = yield

      footer
        p
          |&copy; Company 2015

= render 'layouts/google_tracker'

javascript:
  $(document).ready(function(ret, status){
      $(".timeago").timeago();
  });

app/views/layouts/application.html.slim
/!DOCTYPE html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title = content_for?(:title) ? "#{yield(:title)} | #{Settings.site.title}" : Settings.site.title
    = csrf_meta_tags

    meta name="renderer" content="webkit"
    meta name="author" content="@chad_lwm"
    meta name="description" content="#{Settings.site.description}"
    meta name="keywords" content="techer, techerman, techer man, blog"
    link rel="author" href="/humans.txt"
    
    = content_for?(:metas) ? yield(:metas) : ''

    /!-- Le HTML5 shim, for IE6-8 support of HTML elements
    |<!--[if lt IE 9]>
    | <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    |<![endif]-->

    /!-- For third-generation iPad with high-resolution Retina display:
    /!-- Size should be 144 x 144 pixels
    /!= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'

    /!-- For iPhone with high-resolution Retina display:
    /!-- Size should be 114 x 114 pixels
    /!= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'

    /!-- For first- and second-generation iPad:
    /!-- Size should be 72 x 72 pixels
    /!= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'

    /!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    /!-- Size should be 57 x 57 pixels
    /!= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'


    /!-- For all other devices
    /!-- Size should be 32 x 32 pixels
    = favicon_link_tag '/favicon.ico', :rel => 'shortcut icon'

    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

  body
    header.navbar.navbar-static-top.navbar-inverse style="margin-bottom:0;"
      div.container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to Settings.site.title, root_path, class: 'navbar-brand'
        div.navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li class="#{ nav_active :posts, controller_name }"
              = link_to "Posts", posts_path


          ul.nav.navbar-nav.navbar-right
            - if current_user
              li.dropdown
                a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-expanded="false" 
                  = current_user.display_name
                  |&nbsp;
                  span.caret
                ul class="dropdown-menu" role="menu"
                  - if can? :new, Post
                    li
                      = link_to "撰写文章", new_admin_post_path, target: '_blank'
                  - if can? :read, :dashboard
                    li
                      = link_to "进入后台", admin_root_path, target: '_blank'
                  - if can? :edit, current_user
                    li
                      = link_to "我的账号", edit_admin_user_path(current_user), target: '_blank'
                  li
                    = link_to "注销登录", destroy_user_session_path, method: :delete
            - else
              li
                = link_to '登录', new_user_session_path

    = yield
    = render 'layouts/footer'
    = render 'layouts/google_tracker'
    = render 'layouts/script'
    / = render_cell :side, :search